name: deploy-sandbox

on:
  push:
    branches:
      - master
jobs:
  SSH:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          script: |
            cd Front
            git reset --hard
            git checkout master
            git fetch
            git pull
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm run build
